# Generated by Django 5.0.6 on 2024-05-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookTestRode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CT", "Chhattisgarh"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("MH", "Maharashtra"),
                            ("MP", "Madhya Pradesh"),
                            ("MN", "Manipur"),
                            ("ML", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("NL", "Nagaland"),
                            ("OR", "Odisha"),
                            ("PB", "Punjab"),
                            ("RJ", "Rajasthan"),
                            ("SK", "Sikkim"),
                            ("TN", "Tamil Nadu"),
                            ("TR", "Tripura"),
                            ("TG", "Telangana"),
                            ("UP", "Uttar Pradesh"),
                            ("UT", "Uttarakhand"),
                            ("WB", "West Bengal"),
                            ("AN", "Andaman & Nicobar (UT)"),
                            ("CH", "Chandigarh (UT)"),
                            ("DN", "Dadra & Nagar Haveli and Daman & Diu (UT)"),
                            ("DL", "Delhi [National Capital Territory (NCT)]"),
                            ("JK", "Jammu & Kashmir (UT)"),
                            ("LA", "Ladakh (UT)"),
                            ("LD", "Lakshadweep (UT)"),
                            ("PY", "Puducherry (UT)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("purpose", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
