# Generated by Django 5.0.6 on 2024-05-28 06:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_booktestrode"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog/image/"),
                ),
                ("title", models.CharField(max_length=200)),
                ("content_sort", models.CharField(max_length=200)),
                ("content", ckeditor.fields.RichTextField()),
                ("date", models.DateTimeField()),
                ("author", models.CharField(max_length=100)),
                ("click_count", models.IntegerField(default=0)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
            ],
        ),
    ]
