# Generated by Django 5.0.6 on 2024-05-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_job_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
    ]
