# Generated by Django 5.0.6 on 2024-06-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_job_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
            ],
        ),
    ]
