# Generated by Django 5.0.6 on 2024-06-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_dynamicurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicurl",
            name="meta_description",
            field=models.CharField(blank=True, max_length=5000000000, null=True),
        ),
    ]
