# Generated by Django 5.0.6 on 2024-07-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_dynamicurl_meta_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicurl",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
