# Generated by Django 5.0.6 on 2024-07-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_dynamicurl_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicurl",
            name="meta_description",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
